version: "3"
services:

  minio:
    image: ${DOCKER_MINIO_IMAGE_NAME}
    container_name: minio
    volumes:
      - ./data/minio/data:/data:z
    command: minio server /data --console-address 0.0.0.0:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
      - MINIO_REGION_NAME=${MINIO_REGION_NAME}
      - MINIO_BROWSER=${MINIO_BROWSER}
    restart: always
    networks:
      - outline
    ports:
      - 9000:9000
      - 9001:9001
    extra_hosts:
      - "${DOCKER_MINIO_HOSTNAME}:0.0.0.0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

networks:
  outline:
    external: true
