version: "3"
services:

  minio-client:
    image: ${DOCKER_MINIO_CLIENT_IMAGE_NAME}
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias remove local;
      /usr/bin/mc alias set --quiet --api s3v4 local http://outline_minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      /usr/bin/mc mb --quiet ${AWS_S3_UPLOAD_BUCKET_NAME};
      /usr/bin/mc policy set public local/${AWS_S3_UPLOAD_BUCKET_NAME};
      "
    networks:
      - outline

networks:
  outline:
    external: true
