---
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: your-jwt-secret
default_redirection_url: https://docs.example.com

server:
  host: 0.0.0.0
  port: 9091

log:
  level: info

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: docs.example.com
      policy: one_factor

session:
  name: your_session
  secret: jsSD9m87rsXdwDmwtANm85JaBxUGy1BAZ7UI1ZFB6yRpHM87sGK05ZosCaCxz5gW
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: example.com  # Should match whatever your root protected domain is

  redis:
    host: outline-redis
    port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: E6uFHgat1a89PlXshFViDxrw4l5KRmF1LmX43CIVfGb1wO2SJd7XUR7krSJDz5cG
  local:
    path: /config/db.sqlite3

identity_providers:
  oidc:
    ## The other portions of the mandatory OpenID Connect 1.0 configuration go here.
    ## See: https://www.authelia.com/c/oidc
    hmac_secret: LsPWUrxewsJHzS9FptzgKIB3jFFQdPKj85l3NOaqPmnaTAbDcaHnbkiS6mkQ8k20
    issuer_private_key: |
      -----BEGIN RSA PRIVATE KEY-----
      <need create private key see: https://www.authelia.com/reference/guides/generating-secure-values/#generating-an-rsa-keypair>
      -----END RSA PRIVATE KEY-----
    clients:
    - id: outline
      description: Outline
      secret: 'your-username-docs'
      public: false
      authorization_policy: one_factor
      redirect_uris:
        - https://docs.example.com/auth/oidc.callback
      scopes:
        - openid
        - offline_access
        - profile
        - email
      userinfo_signing_algorithm: none      

notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt
...
